# action.yml
name: 'Sqitch'
description: 'Run sqitch'
inputs:
  command:
    description: 'Command to run'
    required: true
  base_dir:
    description: 'Base directory to run from'
    required: false
    default: '.'
  target:
    description: 'Target'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - '--chdir'
    - ${{ inputs.base_dir }}
    - ${{ inputs.target }}
